-- DROP DATABASE semana_cinco;

CREATE DATABASE IF NOT EXISTS semana_cinco;

USE semana_cinco;

CREATE TABLE IF NOT EXISTS usuarios (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
dni CHAR(11) NOT NULL,
tlf INT UNSIGNED,
email VARCHAR(50) UNIQUE NOT NULL,
nombre VARCHAR(50) NOT NULL,
apellidos VARCHAR(150) NOT NULL,
pais VARCHAR(100),
cp INT UNSIGNED,
direccion1 VARCHAR(250),
direccion2 VARCHAR(250)
);

